name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/docker/go-fiber-vue
            git reset --hard
            git pull
            pnpm -C web i --prod
            pnpm -C web run build
            go mod download
            CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/app
            docker build -t portfolio -f build/package/Dockerfile .
            chmod +x ./scripts/deploy.sh
            bash ./scripts/deploy.sh
